spring.application.name=ms-pessoas
server.port=8082

spring.datasource.url=jdbc:h2:mem:ms_pessoas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

app.jwt.secret=MinhaChaveSecretaMuitoGrandeParaTeste123456789
app.jwt.expiration=86400000